package com.baobabplatform.subscriptions.domain;

/** Machine-readable readiness blockers (ADR-SUB-0006 section 58; subscriptions/v1 billingBlocker). */
public enum BillingBlocker {
    CLASSIFICATION_MISSING,
    CLASSIFICATION_UNSUPPORTED,
    CLASSIFICATION_REVISION_CONFLICT,
    BILLING_POLICY_MISSING,
    BILLING_POLICY_UNSUPPORTED,
    PRICING_CONFIGURATION_MISSING,
    CURRENCY_CONFIGURATION_MISSING,
    BILLING_ACCOUNT_MISSING,
    BILLING_PROVIDER_NOT_CONFIGURED,
    PAYMENT_PATH_NOT_READY,
    PAYMENT_METHOD_REQUIRED,
    USAGE_METERING_UNAVAILABLE,
    PROJECTION_SUSPENDED,
    PROJECTION_TERMINATED
}
